# Generated by Django 4.2.2 on 2023-07-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=40)),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField()),
                ('status', models.CharField(default='in-progress', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
        migrations.CreateModel(
            name='SubTast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('status', models.CharField(default='in-progress', max_length=30)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allocator.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allocator.project'),
            preserve_default=False,
        ),
    ]
