# Generated by Django 4.2.2 on 2023-07-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0003_rename_subtast_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
