# Generated by Django 4.2.2 on 2023-07-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0007_alter_notification_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='status',
        ),
        migrations.AddField(
            model_name='subtask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
