# Generated by Django 4.2.2 on 2023-07-13 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0008_remove_subtask_status_subtask_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allocator.usertype'),
            preserve_default=False,
        ),
    ]
