# Generated by Django 4.2.2 on 2023-07-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0009_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
